# Generated by Django 4.2.23 on 2025-07-15 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScreenshotJob',
            fields=[
                ('job_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('webhook_url', models.URLField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
